// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dynform.Models;

namespace dynform.Migrations
{
    [DbContext(typeof(DynformContext))]
    [Migration("20181104095024_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("dynform.Models.Formular", b =>
                {
                    b.Property<int>("FormularId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Datum");

                    b.HasKey("FormularId");

                    b.ToTable("Formulare");
                });

            modelBuilder.Entity("dynform.Models.Typ", b =>
                {
                    b.Property<int>("TypId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nazov");

                    b.HasKey("TypId");

                    b.ToTable("Typy");
                });

            modelBuilder.Entity("dynform.Models.Zaznam", b =>
                {
                    b.Property<int>("ZaznamId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FormularId");

                    b.Property<string>("Obsah");

                    b.Property<int>("TypId");

                    b.HasKey("ZaznamId");

                    b.HasIndex("FormularId");

                    b.ToTable("Zaznamy");
                });

            modelBuilder.Entity("dynform.Models.Zaznam", b =>
                {
                    b.HasOne("dynform.Models.Formular", "Formular")
                        .WithMany("Zaznamy")
                        .HasForeignKey("FormularId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
